services:
  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    ports:
      - '54322:5432'
    volumes:
      - .local/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:7.4
    ports:
      - '6379:6379'
    volumes:
      - .local/redis:/data
