/**
 * CONEXT
 */
export const PG_QUEUE_CLIENT_TOKEN = 'PG_QUEUE_CLIENT_TOKEN'
export const PG_QUEUE_PROCESSOR_TOKEN = 'PG_QUEUE_PROCESSOR_TOKEN'
export const PG_QUEUE_PROCESSOR_OPTIONS_TOKEN =
  'PG_QUEUE_PROCESSOR_OPTIONS_TOKEN'
export const PG_QUEUE_PROCESSOR_WORKER_TOKEN = 'PG_QUEUE_PROCESSOR_WORKER_TOKEN'
